runtime: nodejs20

entrypoint: npm start

service: recial-server

handlers:
  - url: /.*
    secure: always
    script: auto

env_variables:
  NODE_ENV: production
  DATABASE_PRODUCTION_CONNECT_LINK: $(DATABASE_PRODUCTION_CONNECT_LINK)
  ACCESS_TOKEN_SECRET: $(ACCESS_TOKEN_SECRET)
  REFRESH_TOKEN_SECRET: $(REFRESH_TOKEN_SECRET)

instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5

service_account: recial-application@appspot.gserviceaccount.com